const state={me:null,students:[],student:null,page:"home",summary:null,practice:[],token:sessionStorage.getItem("google_id_token")||"",registrations:[],master:[]};
const $=id=>document.getElementById(id);
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const grades=["一年級","二年級","三年級","四年級","五年級","六年級"],groups=["A","B","C","儲備"],instruments=["小提琴","中提琴","大提琴","低音提琴","其他"];
function opts(list,val){return list.map(x=>`<option value="${esc(x)}" ${x===val?"selected":""}>${esc(x)}</option>`).join("")}
function toast(msg){const t=$("toast");if(!t)return;t.textContent=msg;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),1800)}
async function api(url,options={}){const h={"Content-Type":"application/json",...(options.headers||{})};if(state.token)h["X-Google-ID-Token"]=state.token;const r=await fetch(url,{...options,headers:h});const d=await r.json().catch(()=>({}));if(r.status===401){logout(false);throw new Error("登入已失效，請重新使用 Google 登入")};if(!r.ok)throw new Error(d.error||d.message||`HTTP ${r.status}`);return d}
function logout(reload=true){state.token="";state.me=null;state.students=[];state.student=null;sessionStorage.removeItem("google_id_token");if(window.google?.accounts?.id)google.accounts.id.disableAutoSelect();if(reload)renderLogin()}
async function boot(){if(!state.token){renderLogin();return}try{await loadProfile()}catch(e){renderLogin(e.message)}}
async function loadProfile(){state.me=await api("/api/me");state.students=await api("/api/students");state.student=state.students[0]||null;if(state.me.role==="admin"){state.page="admin";await loadAdmin()}else if(state.me.role==="sectionTeacher")state.page="section";else if(state.me.role==="privateTeacher")state.page="private";else state.page="home";if(state.me.role==="parent"&&state.student)await refreshStudent();render()}
async function loadAdmin(){const [r,m]=await Promise.all([api("/api/student-registration?status=pending"),api("/api/student-master")]);state.registrations=r.items||[];state.master=m.items||[]}
async function refreshStudent(){if(!state.student)return;const month=new Date().toISOString().slice(0,7);const[sum,logs]=await Promise.all([api(`/api/summary?studentId=${encodeURIComponent(state.student.studentId)}&month=${month}`),api(`/api/practice?studentId=${encodeURIComponent(state.student.studentId)}&month=${month}`)]);state.summary=sum;state.practice=logs.items||[]}
async function renderLogin(error=""){document.getElementById("app").innerHTML=`<div class="login-wrap"><div class="login-card"><div class="logo">🎻</div><h1>聖心小學弦樂團</h1><p>Google Gmail 登入版 v3<br>家長、老師與管理員共用入口</p>${error?`<div class="error">${esc(error)}</div>`:""}<div id="googleBtn" style="display:flex;justify-content:center;margin-top:18px"></div><div class="notice" style="margin-top:16px">第一次登入若尚未綁定學生，可直接填寫學生資料送交管理員確認。</div></div></div>`;try{const cfg=await fetch("/api/config").then(r=>r.json());if(!cfg.googleClientId){$("googleBtn").innerHTML='<div class="error">尚未設定 GOOGLE_CLIENT_ID</div>';return}let n=0;const wait=setInterval(()=>{n++;if(window.google?.accounts?.id){clearInterval(wait);google.accounts.id.initialize({client_id:cfg.googleClientId,callback:async res=>{state.token=res.credential;sessionStorage.setItem("google_id_token",state.token);try{await loadProfile()}catch(e){renderLogin(e.message)}}});google.accounts.id.renderButton($("googleBtn"),{theme:"outline",size:"large",shape:"pill",text:"signin_with",locale:"zh_TW",width:280})}else if(n>50){clearInterval(wait);$("googleBtn").innerHTML='<div class="error">Google 登入元件載入失敗</div>'}},100)}catch(e){$("googleBtn").innerHTML=`<div class="error">${esc(e.message)}</div>`}}
function roleText(){return({parent:"家長／學生",sectionTeacher:"分部老師",privateTeacher:"個別課老師",admin:"管理員",unassigned:"尚未綁定"}[state.me?.role]||"使用者")}
function navBtn(p,i,l){return `<button class="${state.page===p?"active":""}" onclick="go('${p}')"><span>${i}</span>${l}</button>`}
function nav(){const r=state.me.role;if(r==="parent")return `<nav class="nav">${navBtn("home","🏠","首頁")}${navBtn("practice","⏱️","自主打卡")}${navBtn("record","📊","紀錄")}${navBtn("register","➕","新增學生")}</nav>`;if(r==="sectionTeacher")return `<nav class="nav">${navBtn("section","🎼","分部點名")}${navBtn("help","ℹ️","說明")}<button></button><button></button></nav>`;if(r==="privateTeacher")return `<nav class="nav">${navBtn("private","🎻","個別課")}${navBtn("help","ℹ️","說明")}<button></button><button></button></nav>`;if(r==="admin")return `<nav class="nav">${navBtn("admin","📈","Dashboard")}${navBtn("students","👥","學生主檔")}${navBtn("scores","🧮","考核")}${navBtn("help","ℹ️","說明")}</nav>`;return `<nav class="nav">${navBtn("home","🏠","登記")}${navBtn("help","ℹ️","說明")}<button></button><button></button></nav>`}
function shell(content){return `<div class="shell"><header class="top"><div class="brand">🎻 聖心小學弦樂團</div><div class="sub">Google Gmail 登入版 v3</div><div class="userrow"><div><small>${esc(state.me.displayName||state.me.email)}</small><span class="role">${roleText()}</span></div><button class="logout" onclick="logout()">登出</button></div></header><main class="main">${content}</main>${nav()}</div>`}
async function go(p){state.page=p;if(["home","practice","record"].includes(p)&&state.student)await refreshStudent();if(state.me.role==="admin"&&["admin","students"].includes(p))await loadAdmin();render()}
function scoreItem(n,s,v,c="ok"){return `<div class="item"><div><b>${esc(n)}</b><small>${esc(s)}</small></div><span class="badge ${c}">${esc(v)}</span></div>`}
function registrationForm(){return `<div class="card"><h2>第一次登入｜學生資料登記</h2><div class="notice">登入 Gmail：${esc(state.me.email)}<br>送出後由管理員確認；核准後 Gmail 才會正式綁定學生。</div><label>家長姓名</label><input id="rParent" value="${esc(state.me.displayName||"")}"><label>與學生關係</label><select id="rRel"><option>父親</option><option>母親</option><option>監護人</option><option>其他</option></select><label>學生姓名</label><input id="rName"><div class="row2"><div><label>年級</label><select id="rGrade">${opts(grades,"三年級")}</select></div><div><label>團別</label><select id="rGroup">${opts(groups,"B")}</select></div></div><label>樂器類別</label><select id="rInst">${opts(instruments,"小提琴")}</select><label>學年度（選填）</label><input id="rYear" placeholder="例：115"><div class="check"><input id="rConsent" type="checkbox"><div>我同意此資料僅用於弦樂團學生身分、點名、練習與考核管理。</div></div><button class="primary" onclick="submitRegistration()">送出學生資料</button></div>`}
async function submitRegistration(){if(!$("rConsent").checked){toast("請先勾選資料使用確認");return}const body={parentName:$("rParent").value,relationship:$("rRel").value,studentName:$("rName").value,grade:$("rGrade").value,groupName:$("rGroup").value,instrument:$("rInst").value,schoolYear:$("rYear").value,consent:true};try{await api("/api/student-registration",{method:"POST",body:JSON.stringify(body)});toast("✅ 已送出，等待管理員確認");state.page="home";render()}catch(e){toast("❌ "+e.message)}}
function home(){if(state.me.role==="unassigned")return registrationForm();if(!state.student)return `<div class="card"><div class="notice">目前帳號尚未綁定學生。</div></div>`;const s=state.summary||{},rate=Math.round((s.practiceRate||0)*1000)/10;return `<div class="card hero"><div class="student"><div class="studentleft"><div class="avatar">${esc(state.student.name?.[0]||"學")}</div><div><div class="name">${esc(state.student.name)}</div><div class="muted">${esc(state.student.groupName)}團｜${esc(state.student.instrument)}｜${esc(state.student.grade)}</div></div></div><div class="pill">${new Date().getMonth()+1}月</div></div><div class="grid"><div class="kpi"><b>${s.practiceQualifiedDays||0}</b><span>自主練習達標天數</span></div><div class="kpi"><b>${s.practiceMinutes||0}</b><span>累計練習分鐘</span></div><div class="kpi"><b>${s.sectionPresent||0} / ${s.sectionTotal||0}</b><span>分部團練</span></div><div class="kpi"><b>${s.privatePresent||0} / ${s.privateTotal||0}</b><span>個別課</span></div></div><div style="margin-top:12px;font-size:12px;font-weight:800">自主練習達標率 <span style="float:right">${rate}%</span></div><div class="progress"><i style="width:${Math.min(rate,100)}%"></i></div></div><div class="card"><h2>今天要做什麼？</h2><div class="notice">年級、團別與樂器資料由學生主檔管理，之後異動不會影響既有點名／練習紀錄。</div><button class="primary" onclick="go('practice')">立即自主練習打卡</button></div>`}
function calcMinutes(s,e){if(!s||!e)return 0;const[a,b]=s.split(":").map(Number),[c,d]=e.split(":").map(Number);let m=(c*60+d)-(a*60+b);if(m<0)m+=1440;return m}
function practicePage(){const today=new Date().toISOString().slice(0,10),logs=state.practice.slice(0,8);return `<div class="card"><h2>自主練習打卡</h2><div class="notice">${esc(state.student?.name)}｜${esc(state.student?.groupName)}團｜${esc(state.student?.instrument)}</div><label>練習日期</label><input id="pDate" type="date" value="${today}"><div class="row2"><div><label>開始時間</label><input id="pStart" type="time" value="18:00" oninput="updateMinutes()"></div><div><label>結束時間</label><input id="pEnd" type="time" value="18:20" oninput="updateMinutes()"></div></div><div class="minutes"><div><div class="muted">本次練習時間</div><strong><span id="pMins">20</span> 分鐘</strong></div><span id="pQual" class="badge ok">✅ 已達標</span></div><label>練習內容／曲目</label><textarea id="pContent" rows="3"></textarea><label>練習重點</label><select id="pFocus"><option>音階／基本功</option><option>團練曲目</option><option>考試曲</option><option>節奏／視奏</option><option>其他</option></select><div class="check"><input id="pConfirm" type="checkbox"><div>家長確認：我確認學生已完成上述自主練習。</div></div><button class="primary" onclick="savePractice()">送出今天的打卡</button></div><div class="card"><h2>最近打卡</h2>${logs.length?logs.map(x=>scoreItem(`${x.practiceDate}｜${x.practiceContent||"自主練習"}`,`${x.startTime}～${x.endTime}｜${x.minutes} 分鐘`,x.qualified?"達標":"未達",x.qualified?"ok":"bad")).join(""):`<div class="notice">本月尚無紀錄。</div>`}</div>`}
function updateMinutes(){const m=calcMinutes($("pStart").value,$("pEnd").value);$("pMins").textContent=m;$("pQual").className=`badge ${m>=15?"ok":"bad"}`;$("pQual").textContent=m>=15?"✅ 已達標":"⚠️ 未達 15 分鐘"}
async function savePractice(){if(!$("pConfirm").checked){toast("請先完成家長確認");return}const body={studentId:state.student.studentId,practiceDate:$("pDate").value,startTime:$("pStart").value,endTime:$("pEnd").value,practiceContent:$("pContent").value.trim(),focus:$("pFocus").value,parentConfirmed:true};try{await api("/api/practice",{method:"POST",body:JSON.stringify(body)});toast("✅ 自主練習已送出");await refreshStudent();render()}catch(e){toast("❌ "+e.message)}}
function recordPage(){const s=state.summary||{};return `<div class="card hero"><h2>${esc(state.student?.name)}｜學習紀錄</h2><div class="score">${s.weightedScore??"—"}</div><div class="muted">目前月統計</div></div><div class="card">${scoreItem("自主練習達標","每日 ≥ 15 分鐘",`${s.practiceQualifiedDays||0} 天`)}${scoreItem("自主練習時數","累計",`${Math.floor((s.practiceMinutes||0)/60)} 小時 ${(s.practiceMinutes||0)%60} 分`)}${scoreItem("分部團練","老師確認",`${s.sectionPresent||0} / ${s.sectionTotal||0}`)}${scoreItem("個別課","老師確認",`${s.privatePresent||0} / ${s.privateTotal||0}`)}</div>`}
function sectionPage(){const today=new Date().toISOString().slice(0,10);return `<div class="card"><h2>分部團練點名</h2><label>上課日期</label><input id="sDate" type="date" value="${today}"><label>聲部</label><input id="sSection" value="${esc(state.me.section||"")}"></div><div class="card"><h2>學生名單</h2>${state.students.map(s=>`<div class="item"><div><b>${esc(s.name)}</b><small>${esc(s.groupName)}團｜${esc(s.instrument)}</small></div><select id="att_${s.studentId}" class="status-select"><option value="present">出席</option><option value="late">遲到</option><option value="leave">請假</option><option value="absent">缺席</option><option value="cancelled">停課</option></select></div>`).join("")}<button class="primary" onclick="saveSection()">儲存本次點名</button></div>`}
async function saveSection(){const items=state.students.map(s=>({studentId:s.studentId,status:$(`att_${s.studentId}`).value,minutes:$(`att_${s.studentId}`).value==="absent"?0:45}));try{await api("/api/section-attendance",{method:"POST",body:JSON.stringify({sessionDate:$("sDate").value,section:$("sSection").value,items})});toast("✅ 分部點名已儲存")}catch(e){toast("❌ "+e.message)}}
function privatePage(){const today=new Date().toISOString().slice(0,10);return `<div class="card"><h2>個別課紀錄</h2><label>學生</label><select id="iStudent">${state.students.map(s=>`<option value="${s.studentId}">${esc(s.name)}｜${esc(s.instrument)}</option>`).join("")}</select><label>上課日期</label><input id="iDate" type="date" value="${today}"><div class="row2"><div><label>狀態</label><select id="iStatus"><option value="present">出席</option><option value="late">遲到</option><option value="leave">請假</option><option value="absent">缺席</option></select></div><div><label>分鐘</label><input id="iMinutes" type="number" value="50"></div></div><label>課程內容</label><textarea id="iContent" rows="3"></textarea><button class="primary" onclick="savePrivate()">儲存個別課紀錄</button></div>`}
async function savePrivate(){try{await api("/api/private-lesson",{method:"POST",body:JSON.stringify({studentId:$("iStudent").value,lessonDate:$("iDate").value,status:$("iStatus").value,minutes:Number($("iMinutes").value||0),lessonContent:$("iContent").value})});toast("✅ 個別課紀錄已儲存")}catch(e){toast("❌ "+e.message)}}
function pendingCard(r){return `<div class="card"><h2>${esc(r.studentName)}｜待審核</h2><div class="notice">家長：${esc(r.parentName)}（${esc(r.relationship)}）<br>${esc(r.parentEmail)}</div><label>學生姓名</label><input id="rn_${r.registrationId}" value="${esc(r.studentName)}"><div class="row2"><div><label>年級</label><select id="rg_${r.registrationId}">${opts(grades,r.grade)}</select></div><div><label>團別</label><select id="rgrp_${r.registrationId}">${opts(groups,r.groupName)}</select></div></div><label>樂器</label><select id="ri_${r.registrationId}">${opts(instruments,r.instrument)}</select><label>學年度</label><input id="ry_${r.registrationId}" value="${esc(r.schoolYear||"")}"><label>對應既有學生（已有名單時使用）</label><select id="rm_${r.registrationId}"><option value="">建立新學生主檔</option>${state.master.map(s=>`<option value="${esc(s.studentId)}">${esc(s.name)}｜${esc(s.grade)}｜${esc(s.groupName)}團｜${esc(s.instrument)}</option>`).join("")}</select><div class="row2"><button class="primary" onclick="approveReg('${r.registrationId}')">核准並綁定</button><button class="secondary" style="margin-top:14px" onclick="rejectReg('${r.registrationId}')">退回</button></div></div>`}
async function approveReg(id){const body={registrationId:id,action:"approve",studentName:$(`rn_${id}`).value,grade:$(`rg_${id}`).value,groupName:$(`rgrp_${id}`).value,instrument:$(`ri_${id}`).value,schoolYear:$(`ry_${id}`).value,studentId:$(`rm_${id}`).value};try{await api("/api/student-registration",{method:"PATCH",body:JSON.stringify(body)});toast("✅ 已核准並綁定");await loadAdmin();render()}catch(e){toast("❌ "+e.message)}}
async function rejectReg(id){if(!confirm("確定退回此登記？"))return;try{await api("/api/student-registration",{method:"PATCH",body:JSON.stringify({registrationId:id,action:"reject"})});toast("已退回");await loadAdmin();render()}catch(e){toast("❌ "+e.message)}}
function adminPage(){return `<div class="card hero"><h2>管理員 Dashboard</h2><div class="grid"><div class="kpi"><b>${state.master.length}</b><span>學生主檔</span></div><div class="kpi"><b>${state.registrations.length}</b><span>待審核</span></div><div class="kpi"><b>80%</b><span>考試</span></div><div class="kpi"><b>10/5/5</b><span>練習／個課／分部</span></div></div></div>${state.registrations.length?`<h2>待審核學生</h2>${state.registrations.map(pendingCard).join("")}`:`<div class="card"><div class="notice">目前沒有待審核資料。</div></div>`}`}
function studentEdit(s){return `<div class="card"><h2>${esc(s.name)} <span class="badge ${s.status==="active"?"ok":"warn"}">${esc(s.studentId)}</span></h2><label>姓名</label><input id="sn_${s.studentId}" value="${esc(s.name)}"><div class="row2"><div><label>年級</label><select id="sg_${s.studentId}">${opts(grades,s.grade)}</select></div><div><label>團別</label><select id="sgrp_${s.studentId}">${opts(groups,s.groupName)}</select></div></div><label>樂器</label><select id="si_${s.studentId}">${opts(instruments,s.instrument)}</select><div class="row2"><div><label>學年度</label><input id="sy_${s.studentId}" value="${esc(s.schoolYear||"")}"></div><div><label>狀態</label><select id="ss_${s.studentId}"><option value="active" ${s.status==="active"?"selected":""}>在團</option><option value="inactive" ${s.status==="inactive"?"selected":""}>停用／離團</option></select></div></div><button class="primary" onclick="saveStudent('${s.studentId}')">儲存異動</button></div>`}
function studentsPage(){return `<div class="card"><h2>學生主檔管理</h2><div class="notice">年級、團別、樂器皆可後續修改；每次異動會寫入 StudentHistory，不會改掉過去點名與練習紀錄。</div></div>${state.master.map(studentEdit).join("")||'<div class="card"><div class="notice">尚無學生主檔。之後可以匯入目前弦樂團名單。</div></div>'}`}
async function saveStudent(id){const body={studentId:id,name:$(`sn_${id}`).value,grade:$(`sg_${id}`).value,groupName:$(`sgrp_${id}`).value,instrument:$(`si_${id}`).value,schoolYear:$(`sy_${id}`).value,status:$(`ss_${id}`).value};try{await api("/api/student-master",{method:"PATCH",body:JSON.stringify(body)});toast("✅ 學生主檔已更新");await loadAdmin();render()}catch(e){toast("❌ "+e.message)}}
function helpPage(){return `<div class="card"><h2>系統說明</h2><div class="notice">Gmail 只用來辨識家長／老師／管理員；學生資料存在 StudentMaster。年級升級、A/B 團異動、換樂器時，只更新學生主檔即可。</div></div>`}
function render(){let c;if(state.me.role==="admin")c=state.page==="students"?studentsPage():state.page==="help"?helpPage():adminPage();else if(state.me.role==="sectionTeacher")c=state.page==="help"?helpPage():sectionPage();else if(state.me.role==="privateTeacher")c=state.page==="help"?helpPage():privatePage();else if(state.page==="practice")c=practicePage();else if(state.page==="record")c=recordPage();else if(state.page==="register")c=registrationForm();else if(state.page==="help")c=helpPage();else c=home();document.getElementById("app").innerHTML=shell(c)}
boot();
