(()=>{
  const ua=navigator.userAgent||"";
  const isIOS=/iPhone|iPad|iPod/i.test(ua);
  const isAndroid=/Android/i.test(ua);
  const isLine=/\bLine\//i.test(ua);
  const isSocial=/FBAN|FBAV|Instagram|MicroMessenger|Twitter|Messenger|TikTok|Snapchat|ChatGPT/i.test(ua);
  const isIOSWebView=isIOS&&/AppleWebKit/i.test(ua)&&!/Safari/i.test(ua);
  const isAndroidWebView=isAndroid&&(/;\s*wv\)/i.test(ua)||/\bwv\b/i.test(ua));
  const embedded=isLine||isSocial||isIOSWebView||isAndroidWebView;
  const current=new URL(location.href);
  if(current.searchParams.get("google_redirect")==="1"){sessionStorage.setItem("google_id_token","cookie-session");current.searchParams.delete("google_redirect");history.replaceState({},"",current.pathname+(current.search?current.search:"")+current.hash)}
  function cleanUrl(){const u=new URL(location.href);u.searchParams.delete("openExternalBrowser");u.searchParams.delete("openInAppBrowser");u.searchParams.delete("google_redirect");return u.toString()}
  function lineExternalUrl(){const u=new URL(cleanUrl());u.searchParams.set("openExternalBrowser","1");return u.toString()}
  window.copyOrchestraUrl=async()=>{const url=cleanUrl();try{await navigator.clipboard.writeText(url);alert("網址已複製，請貼到 Safari 或 Chrome 開啟。")}catch{const t=document.createElement("textarea");t.value=url;document.body.appendChild(t);t.select();document.execCommand("copy");t.remove();alert("網址已複製，請貼到 Safari 或 Chrome 開啟。")}};
  if(embedded){const platform=isIOS?"Safari":isAndroid?"Chrome":"外部瀏覽器";const action=isLine?`<a class="primary" style="display:block;text-align:center;text-decoration:none" href="${lineExternalUrl()}">用 ${platform} 開啟</a>`:`<button class="primary" onclick="copyOrchestraUrl()">複製網址，用 ${platform} 開啟</button>`;document.getElementById("app").innerHTML=`<div class="login-wrap"><div class="login-card"><div class="logo">🎻</div><h1>聖心小學弦樂團</h1><p>Google Gmail 登入</p><div class="error" style="margin-top:16px"><b>目前是在 App 內建瀏覽器中開啟</b><br><br>Google 為保護帳號，不支援 Android／iOS WebView 登入，因此可能只看到白畫面。</div><div class="notice" style="margin-top:12px">請改用 <b>${platform}</b> 開啟本系統，再按「使用 Google 帳戶登入」。${isLine?"<br><br>下方按鈕會要求 LINE 改用外部瀏覽器開啟。":""}</div>${action}<button class="secondary" style="width:100%;margin-top:10px" onclick="copyOrchestraUrl()">複製網站網址</button></div></div>`;return}
  function appendScript(src,onload){const s=document.createElement("script");s.src=src;s.defer=true;if(onload)s.onload=onload;document.body.appendChild(s)}
  function loadApp(){appendScript("/app-v3.js?v=20260917-0215",()=>{appendScript("/roster-support.js",()=>{appendScript("/section-support.js?v=20260917-1205",()=>{appendScript("/student-number-support.js?v=20260918-1105",()=>{appendScript("/student-change-admin.js?v=20260918-1015",()=>{appendScript("/parent-link-admin.js",()=>{appendScript("/teacher-support.js?v=20260916-2245",()=>{appendScript("/teacher-settings.js?v=20260915-1415",()=>{appendScript("/private-student-bottom-back.js?v=20260915-1432",()=>{appendScript("/teacher-admin.js?v=20260918-0125",()=>{appendScript("/batch-upgrade.js",()=>{appendScript("/roster-import.js?v=20260915-1135",()=>{appendScript("/attendance-support.js?v=20260915-0915",()=>{appendScript("/attendance-edit.js",()=>{appendScript("/teacher-navigation.js?v=20260917-0025",()=>{appendScript("/comprehensive-support.js?v=20260915-0915",()=>{appendScript("/practice-progress.js?v=20260917-0040",()=>{appendScript("/practice-timer.js?v=20260918-0725",()=>{appendScript("/private-lesson-confirmation.js?v=20260917-0215",()=>appendScript("/admin-operations.js?v=20260915-0915",()=>appendScript("/admin-followup-summary-fix.js?v=20260917-1320",()=>appendScript("/system-backup.js?v=20260915-1225",()=>appendScript("/parent-semester-attendance.js?v=20260917-0300",()=>appendScript("/parent-home-summary.js?v=20260918-0205",()=>appendScript("/school-access.js?v=20260918-0005",()=>appendScript("/school-access-audit-admin.js?v=20260918-0005",()=>appendScript("/school-access-refresh-fix.js?v=20260915-2340")))))))));});});});});});});});});});});});});});});});});});})}
  function installIOSRedirectMode(){let tries=0;const timer=setInterval(()=>{tries++;if(window.google?.accounts?.id?.initialize){clearInterval(timer);const nativeInitialize=window.google.accounts.id.initialize.bind(window.google.accounts.id);window.google.accounts.id.initialize=(config={})=>{const {callback,...rest}=config;return nativeInitialize({...rest,ux_mode:"redirect",login_uri:`${location.origin}/api/google-login`})};loadApp()}else if(tries>120){clearInterval(timer);loadApp()}},50)}
  document.addEventListener("click",async e=>{const btn=e.target.closest?.(".logout");if(!btn)return;e.preventDefault();e.stopImmediatePropagation();try{await fetch("/api/google-logout",{method:"POST"})}catch{}sessionStorage.removeItem("google_id_token");location.href="/"},true);
  if(isIOS)installIOSRedirectMode();else loadApp();
})();