import { app } from "@azure/functions";
import { TableClient, TableServiceClient } from "@azure/data-tables";
import { getAccess, getTenantContext, getStudentAliasInfo, json } from "../lib/auth.js";
import { ensureTenantTables, listActivityRange, activityStudentId, listStudentMaster, getTeacherDirectory, getTenantDirectory, defaultTenantId, tenantIdValue, tenantSchoolPartition } from "../lib/storage.js";

const settingsTableName=()=>process.env.SYSTEM_SETTINGS_TABLE||"SystemSettings";
const accessLogTableName=()=>process.env.SCHOOL_ACCESS_LOG_TABLE||"SchoolAccessLog";
const conn=()=>process.env.STORAGE_CONNECTION_STRING;
let settingsReady=false,accessLogReady=false;
function clean(v,max=120){return String(v||"").trim().slice(0,max)}
function taipeiDate(){return new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Taipei",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date())}
function normalizeEmails(list=[]){const values=Array.isArray(list)?list:String(list||"").split(/[\n,;]+/);return [...new Set(values.map(x=>String(x||"").trim().toLowerCase()).filter(x=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(x)))].sort()}
async function ensureSettings(){if(settingsReady)return;if(!conn())throw new Error("STORAGE_CONNECTION_STRING 未設定");const service=TableServiceClient.fromConnectionString(conn());try{await service.createTable(settingsTableName())}catch(e){if(e.statusCode!==409)throw e}settingsReady=true}
async function ensureAccessLog(){if(accessLogReady)return;if(!conn())throw new Error("STORAGE_CONNECTION_STRING 未設定");const service=TableServiceClient.fromConnectionString(conn());try{await service.createTable(accessLogTableName())}catch(e){if(e.statusCode!==409)throw e}accessLogReady=true}
function settingsClient(){return TableClient.fromConnectionString(conn(),settingsTableName())}
function accessLogClient(){return TableClient.fromConnectionString(conn(),accessLogTableName())}
function logRowKey(){return `${new Date().toISOString().replace(/[-:.TZ]/g,"")}_${Math.random().toString(36).slice(2,8)}`}
function schoolSettingsPartition(schoolId){return `SCHOOL|${tenantSchoolPartition(schoolId)}`}
function viewerPartition(schoolId,email){return `${tenantSchoolPartition(schoolId)}|viewer|${String(email||"").trim().toLowerCase()}`}
async function recordSchoolAccess(email,eventType,detail="",schoolId=defaultTenantId()){await ensureAccessLog();const now=new Date().toISOString(),sid=tenantSchoolPartition(schoolId);await accessLogClient().createEntity({partitionKey:viewerPartition(sid,email),rowKey:logRowKey(),schoolId:sid,viewerEmail:String(email||"").trim().toLowerCase(),eventType,detail:clean(detail,120),createdAt:now});return now}
async function schoolAccessStats(emails=[],schoolId=defaultTenantId()){
  await ensureAccessLog();const sid=tenantSchoolPartition(schoolId),month=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Taipei",year:"numeric",month:"2-digit"}).format(new Date()),result=[];
  for(const email of emails){
    const byKey=new Map(),partitions=[viewerPartition(sid,email)];if(sid===defaultTenantId())partitions.push(String(email).trim().toLowerCase());
    for(const partition of partitions){const safe=partition.replaceAll("'","''");for await(const e of accessLogClient().listEntities({queryOptions:{filter:`PartitionKey eq '${safe}'`}}))byKey.set(`${partition}|${String(e.rowKey||"")}`,{type:String(e.eventType||""),at:String(e.createdAt||""),detail:String(e.detail||"")})}
    const events=[...byKey.values()].sort((a,b)=>b.at.localeCompare(a.at)),logins=events.filter(x=>x.type==="login"),exports=events.filter(x=>x.type==="attendance_export"),monthlyLogins=logins.filter(x=>x.at.slice(0,7)===month),monthlyExports=exports.filter(x=>x.at.slice(0,7)===month);
    result.push({email,lastLoginAt:logins[0]?.at||null,lastAttendanceExportAt:exports[0]?.at||null,month,monthlyLoginCount:monthlyLogins.length,monthlyAttendanceExportCount:monthlyExports.length,monthlyLogins:monthlyLogins.map(x=>x.at),monthlyAttendanceExports:monthlyExports.map(x=>({at:x.at,date:x.detail}))});
  }
  return result;
}
async function getSchoolEmails(schoolId=defaultTenantId()){
  await ensureSettings();const sid=tenantSchoolPartition(schoolId),partition=schoolSettingsPartition(sid);
  try{const e=await settingsClient().getEntity(partition,"schoolAccess");let list=[];try{list=JSON.parse(String(e.emailsJson||"[]"))}catch{list=[]}return normalizeEmails(list)}catch(e){
    if(e.statusCode!==404)throw e;
    if(sid===defaultTenantId())try{const legacy=await settingsClient().getEntity("SYSTEM","schoolAccess");let list=[];try{list=JSON.parse(String(legacy.emailsJson||"[]"))}catch{list=[]}const normalized=normalizeEmails(list);await settingsClient().upsertEntity({partitionKey:partition,rowKey:"schoolAccess",schoolId:sid,emailsJson:JSON.stringify(normalized),updatedAt:String(legacy.updatedAt||new Date().toISOString()),updatedBy:String(legacy.updatedBy||"legacy-migration")},"Merge");return normalized}catch(legacyError){if(legacyError.statusCode!==404)throw legacyError}
    return [];
  }
}
async function saveSchoolEmails(emails,updatedBy="",schoolId=defaultTenantId()){await ensureSettings();const sid=tenantSchoolPartition(schoolId),list=normalizeEmails(emails);const entity={partitionKey:schoolSettingsPartition(sid),rowKey:"schoolAccess",schoolId:sid,emailsJson:JSON.stringify(list),updatedAt:new Date().toISOString(),updatedBy:clean(updatedBy,160)};await settingsClient().upsertEntity(entity,"Merge");return {schoolId:sid,emails:list,updatedAt:entity.updatedAt,updatedBy:entity.updatedBy}}
async function isSchoolViewer(email,schoolId=defaultTenantId()){return (await getSchoolEmails(schoolId)).includes(String(email||"").trim().toLowerCase())}
function studentView(e){return {studentId:e.rowKey,name:e.studentName,grade:e.grade,groupName:e.groupName,instrument:e.instrument,section:e.section||"待確認",schoolYear:e.schoolYear||"",status:e.status||"active"}}
async function canonicalId(id,students,cache,schoolId){const key=String(id||"");if(students.has(key))return key;if(cache.has(key))return cache.get(key);try{const a=await getStudentAliasInfo(key,schoolId);const c=String(a.canonicalStudentId||key);cache.set(key,c);return c}catch{cache.set(key,key);return key}}
async function teacherName(email,cache,schoolId){const key=String(email||"").trim().toLowerCase();if(!key)return "";if(cache.has(key))return cache.get(key);try{const d=await getTeacherDirectory(key,schoolId);const name=String(d?.teacherName||"").trim()||key;cache.set(key,name);return name}catch{cache.set(key,key);return key}}
async function collectDaily(key,date,schoolId){const latest=new Map();for(const e of await listActivityRange(key,schoolId,"","",date)){const rawStudentId=activityStudentId(e);const classType=key==="ensemble"?"ensemble":key==="comprehensive"?"comprehensive":"section";const row={rawStudentId,eventDate:String(e.eventDate||date),classType,groupName:String(e.groupName||""),section:String(e.section||""),status:String(e.status||""),teacher:String(e.teacher||""),createdAt:String(e.createdAt||""),rowKey:String(e.rowKey||"")};const k=[rawStudentId,row.eventDate,row.classType,row.groupName,row.section].join("|");const old=latest.get(k),stamp=`${row.createdAt}|${row.rowKey}`,oldStamp=old?`${old.createdAt}|${old.rowKey}`:"";if(!old||stamp>=oldStamp)latest.set(k,row)}return [...latest.values()]}
async function viewerContext(request){
  const access=await getAccess(request);
  if(!access.authenticated)return {access,error:json({error:"Unauthorized"},401)};
  if(["admin","globalAdmin","tenantPending","contextDenied"].includes(access.role))return {access,error:json({error:"Forbidden"},403)};
  const requestedSchoolId=tenantIdValue(request.headers.get("x-school-id")),schoolId=requestedSchoolId||tenantIdValue(access.schoolId)||defaultTenantId();
  const tenant=await getTenantDirectory(schoolId);
  if(!tenant||String(tenant.status||"")!=="active")return {access,error:json({error:"此學校尚未啟用"},403)};
  if(!await isSchoolViewer(access.email,schoolId))return {access,error:json({error:"Forbidden"},403)};
  return {access,schoolId,tenant,error:null};
}
app.http("schoolAccessAdmin",{methods:["GET","PATCH"],authLevel:"anonymous",route:"school-access",handler:async(request)=>{const context=await getTenantContext(request);if(context.error)return context.error;const {access:a,schoolId}=context;if(a.role!=="admin")return json({error:"Forbidden"},403);if(request.method==="PATCH"){const body=await request.json();if(!Array.isArray(body.emails))return json({error:"emails 必須為陣列"},400);const raw=body.emails.map(x=>String(x||"").trim()).filter(Boolean),emails=normalizeEmails(raw);if(emails.length!==new Set(raw.map(x=>x.toLowerCase())).size)return json({error:"請確認所有校方帳號皆為有效 Email"},400);return json(await saveSchoolEmails(emails,a.email,schoolId))}const emails=await getSchoolEmails(schoolId);return json({schoolId,emails,accessStats:await schoolAccessStats(emails,schoolId)})}});
app.http("schoolAccessSelf",{methods:["GET"],authLevel:"anonymous",route:"school-access-self",handler:async(request)=>{const context=await viewerContext(request);if(context.error){if(context.error.status===401)return context.error;const a=context.access;return json({allowed:false,email:a?.email||"",role:a?.role||"unassigned"})}const {access:a,schoolId,tenant}=context;try{await recordSchoolAccess(a.email,"login","",schoolId)}catch(e){console.warn("school login audit failed",e?.message||e)}return json({allowed:true,email:a.email,role:"school",schoolId,schoolName:String(tenant.schoolName||schoolId)})}});
app.http("schoolAttendanceExportAudit",{methods:["POST"],authLevel:"anonymous",route:"school-attendance-export-audit",handler:async(request)=>{const context=await viewerContext(request);if(context.error)return context.error;const {access:a,schoolId}=context;let body={};try{body=await request.json()}catch{}const date=clean(body.date||taipeiDate(),20);if(!/^\d{4}-\d{2}-\d{2}$/.test(date))return json({error:"日期格式不正確"},400);try{const createdAt=await recordSchoolAccess(a.email,"attendance_export",date,schoolId);return json({ok:true,schoolId,date,createdAt})}catch(e){console.error("school export audit failed",e);return json({error:"匯出紀錄寫入失敗"},500)}}});
app.http("schoolFollowup",{methods:["GET"],authLevel:"anonymous",route:"school-followup",handler:async(request)=>{let schoolId;const tenantContext=await getTenantContext(request);if(!tenantContext.error&&tenantContext.access.role==="admin")schoolId=tenantContext.schoolId;else{const viewer=await viewerContext(request);if(viewer.error)return viewer.error;schoolId=viewer.schoolId}const date=clean(request.query.get("date")||taipeiDate(),20);if(!/^\d{4}-\d{2}-\d{2}$/.test(date))return json({error:"日期格式不正確"},400);await ensureTenantTables();const masters=await listStudentMaster("",schoolId),students=new Map(masters.map(e=>[String(e.rowKey),studentView(e)])),canonicalCache=new Map(),teacherCache=new Map();const [sectionRows,ensembleRows,comprehensiveRows]=await Promise.all([collectDaily("section",date,schoolId),collectDaily("ensemble",date,schoolId),collectDaily("comprehensive",date,schoolId)]);const latest=new Map();for(const r of [...sectionRows,...ensembleRows,...comprehensiveRows]){const studentId=await canonicalId(r.rawStudentId,students,canonicalCache,schoolId),row={...r,studentId};const k=[studentId,row.eventDate,row.classType,row.groupName,row.section].join("|");const old=latest.get(k),stamp=`${row.createdAt}|${row.rowKey}`,oldStamp=old?`${old.createdAt}|${old.rowKey}`:"";if(!old||stamp>=oldStamp)latest.set(k,row)}const items=[];for(const r of latest.values()){const s=students.get(String(r.studentId))||{studentId:r.studentId,name:`學生 ${r.studentId}`,grade:"",groupName:r.groupName,section:r.section||"待確認",instrument:""};items.push({date:r.eventDate,classType:r.classType,studentId:r.studentId,name:s.name,grade:s.grade,groupName:r.groupName||s.groupName,section:r.classType==="ensemble"?"四分部合班":r.section||s.section||"待確認",instrument:s.instrument,status:r.status,teacherName:await teacherName(r.teacher,teacherCache,schoolId)})}const order={absent:0,leave:1,late:2,present:3,cancelled:4};items.sort((x,y)=>(order[x.status]??9)-(order[y.status]??9)||String(x.classType).localeCompare(String(y.classType))||String(x.groupName).localeCompare(String(y.groupName),"zh-Hant")||String(x.section).localeCompare(String(y.section),"zh-Hant")||String(x.name).localeCompare(String(y.name),"zh-Hant"));const count=status=>items.filter(x=>x.status===status).length;return json({schoolId,date,scope:"00:00-23:59",readOnly:true,items,counts:{total:items.length,present:count("present"),late:count("late"),leave:count("leave"),absent:count("absent"),cancelled:count("cancelled"),followup:count("leave")+count("absent")}})}});
